set shell := ["bash", "-cu"]
set dotenv-path := "../private/.env"
set dotenv-required := true

mastercv := "./tmp/master_cv.md"
cvbody := "./private/parts/body.md"

default:
    @just --list

cfg-create:
    uv run python tools/cfg.py --create

cfg-check path="":
    uv run python tools/cfg.py --check {{ if path == "" { "" } else { "--path " + path } }}

check:
    uv run python tools/process_cv.py --check {{ cvbody }}

fix:
    uv run python tools/process_cv.py --fix {{ mastercv }}

combine:
    cat ./private/parts/header.md > {{ mastercv }}
    printf "\n" >> {{ mastercv }}
    cat {{ cvbody }} >> {{ mastercv }}
    printf "\n" >> {{ mastercv }}
    cat ./private/parts/footer.md >> {{ mastercv }}

run: check combine
    # fix
    uv run python tools/process_cv.py --fix {{ mastercv }}

    # create text to tailor cv for job description
    /home/kirill/prj/gh/job-hunt/tools/prep_for_cv_tail/target/debug/prep_for_tail \
      --cv {{ mastercv }} \
      --prompt ./prompts/tailor_for_description.md \
      --jd ./tmp/jd.txt \
      --output ./tmp/prompt_to_tailor_for_description.md

    # evaluate match
    # cat ./prompt_match.md > "./tmp/prompt_to_match.md"
    # printf "\nCV:\n" >> "./tmp/prompt_to_match.md"
    # cat "./tmp/nvidia_gemini_cv.md" >> "./tmp/prompt_to_match.md"
    # printf "\nJob desription:\n" >> "./tmp/prompt_to_match.md"
    # cat "./tmp/nvidia.txt" >> "./tmp/prompt_to_match.md"

gui:
    /home/kirill/prj/gh/job-hunt/tools/prep_for_cv_tail/target/debug/prep_for_tail_ui

mastercv-pdf:
    uv run python tools/process_cv.py --fix {{ mastercv }}
    @just md2pdf "{{ mastercv }}" "./tmp/master_cv.pdf"

prepare-cv folder name="body.md":
    # flow:

    # use just gui with config
    # create master cv
    # add job description
    # create llm prompt
    # ask llm for description

    uv run python tools/prepare_cv.py --folder {{ folder }} --body "{{ folder }}/{{ name }}"
    @just update-pdf {{ folder }}

prepare-llm folder:
    uv run python tools/prepare_cv.py --llm-prompt --folder {{ folder }}

prepare-llm-for-titles:
    # uv run python tools/prepare_llm_prompt.py --output ./tmp/llm_titles/py.md --tailor-for-title "Python Backend Engineer (Cloud Infrastructure & Microservices)"
    # uv run python tools/prepare_llm_prompt.py --output ./tmp/llm_titles/go.md --tailor-for-title "Golang Backend Engineer (Cloud-Native & Distributed Systems)"
    # uv run python tools/prepare_llm_prompt.py --output ./tmp/llm_titles/sdet.md --tailor-for-title "Software Development Engineer in Test (SDET) / QA Automation"
    # uv run python tools/prepare_llm_prompt.py --output ./tmp/llm_titles/fullstack.md --tailor-for-title "Full-Stack Software Engineer (Modern Web & Cloud Architecture)"
    # uv run python tools/prepare_llm_prompt.py --output ./tmp/llm_titles/platform.md --tailor-for-title "Platform Engineer (Cloud Infrastructure, IaC & DevOps Automation)"

    # @echo "TODO: for each *.md file create *_cv.md file. Hint: use your LLM"
    # @read -p "Press Enter when done... "

    uv run python tools/create_cv_from_titles.py --folder ./tmp/llm_titles

update-pdf folder:
    @just md2pdf "{{ folder }}/gen/cv.md" "{{ folder }}/gen/cv.pdf"

md2pdf input output options="--check --fix":
    uv run python tools/process_cv.py {{ options }} "{{ input }}"
    uv run python tools/md2pdf.py "{{ input }}" --output "{{ output }}"

auto-compose-cv folder:
    # uv run python tools/compose_cv_locally.py {{ folder }} --model gemma4:e2b-ctx32k
    uv run python tools/compose_cv_locally.py {{ folder }} --model "gemma-4-26b-a4b-it"

auto-compose-cv-top-models folder:
    uv run python tools/compose_cv_locally.py {{ folder }} --model "gemma4:e4b-it-qat" --force
    # uv run python tools/compose_cv_locally.py {{ folder }} --model qwen3.5:9b-q4_K_M
    # uv run python tools/compose_cv_locally.py {{ folder }} --model llama3.1:8b-text-q4_K_M
    # uv run python tools/compose_cv_locally.py {{ folder }} --model gemma4:e2b
    # uv run python tools/compose_cv_locally.py {{ folder }} --model qwen3.5:4b-q8_0
    # uv run python tools/compose_cv_locally.py {{ folder }} --model llama3.3:7b-instruct-q4_K_M
    # uv run python tools/compose_cv_locally.py {{ folder }} --model phi4-mini:3.8b-q8_0   
    # uv run python tools/compose_cv_locally.py {{ folder }} --model falcon3:7b

    # uv run python tools/compose_cv_locally.py {{ folder }} --model "gemini-3.1-flash-lite"
    # uv run python tools/compose_cv_locally.py {{ folder }} --model "gemini-3.5-flash"
    # uv run python tools/compose_cv_locally.py {{ folder }} --model "gemma-4-26b-a4b-it"
    # uv run python tools/compose_cv_locally.py {{ folder }} --model "gemma-4-31b-it"

auto-compose-csv path:
    uv run python tools/compose_jobs_from_csv.py --path {{ path }} --folder ./tmp/from_csv --model "gemma4:e2b-ctx32k"
    uv run python tools/compose_jobs_from_csv.py --path {{ path }} --folder ./tmp/from_csv --model "gemma-4-26b-a4b-it"
