model_default_options:
  num_ctx: 16384
  num_predict: 3072
  seed: 42
  keep_alive: 0
  temperature: 0

models:
  - name: "llama3.1:8b-text-q4_K_M"
  - name: "gemma4:e4b-it-qat"
  - name: "llama3.2:3b-instruct-q8_0"
  - name: "qwen2.5:3b-instruct-q8_0"
  - name: "qwen2.5:7b-instruct-q4_K_M"
  - name: "mistral:7b-instruct-v0.3-q4_K_M"
  - name: "qwen3.5:9b-q4_K_M"
  - name: "gemma4:12b-it-qat"
  - name: "qwen3.5:4b-q8_0"
  - name: "llama3.1:8b-instruct-q6_K"
  - name: "gemma2:9b-instruct-q5_K_M"
  - name: "gemma4:e2b"
  - name: "gemma4:e2b-it-qat"
  - name: "deepseek-r1:7b"
  - name: "qwen2.5:7b"
  - name: "qwen2.5-coder:7b"
  - name: "llama3.1:8b"
  - name: "codegemma:7b-code"
  - name: "deepseek-r1:1.5b"

eval_model: "gemma4:e2b-it-qat"
root_dir: "../.."
tmp_output_dir: "{root_dir}/tmp/outputs"
llm_prompt_output_file: "llm_prompt.md"
trulens_db_url: "sqlite:///{root_dir}/tmp/outputs/truelens/default.sqlite"
job1_ground_truth: "{root_dir}/inputs/job1/gt.md"
prepare_llm_prompt_script: "{root_dir}/cv/tools/prepare_llm_prompt.py"

