build:
    ollama create gemma4:e2b-ctx65k -f ./gemma4_e2b_ctx65k
    ollama create gemma4:e2b-it-qat-ctx65k -f ./gemma4_e2b_it_ctx65k
    ollama create gemma4:e4b-it-qat-ctx65k -f ./gemma4_e4b_it_ctx65k
